"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[confirm]
delete_offset = [0, 0, 70, 20]
delete_origin = "center"
delete_title = "Permanently delete {n} selected file{s}?"
overwrite_content = "Will overwrite the following file:"
overwrite_offset = [0, 0, 50, 15]
overwrite_origin = "center"
overwrite_title = "Overwrite file?"
quit_content = "The following task is still running, are you sure you want to quit?"
quit_offset = [0, 0, 50, 15]
quit_origin = "center"
quit_title = "Quit?"
trash_offset = [0, 0, 70, 20]
trash_origin = "center"
trash_title = "Trash {n} selected file{s}?"

[input]
cd_offset = [0, 2, 50, 3]
cd_origin = "top-center"
cd_title = "Change directory:"
create_offset = [0, 2, 50, 3]
create_origin = "top-center"
create_title = ["Create:", "Create (dir):"]
cursor_blink = false
filter_offset = [0, 2, 50, 3]
filter_origin = "top-center"
filter_title = "Filter:"
find_offset = [0, 2, 50, 3]
find_origin = "top-center"
find_title = ["Find next:", "Find previous:"]
rename_offset = [0, 1, 50, 3]
rename_origin = "hovered"
rename_title = "Rename:"
search_offset = [0, 2, 50, 3]
search_origin = "top-center"
search_title = "Search via {n}:"
shell_offset = [0, 2, 50, 3]
shell_origin = "top-center"
shell_title = ["Shell:", "Shell (block):"]

[mgr]
linemode = "none"
mouse_events = ["click", "scroll"]
ratio = [2, 4, 3]
scrolloff = 5
show_hidden = true
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false
sort_translit = false
title_format = "Yazi: {cwd}"

[[open.rules]]
url = "*/"
use = ["edit", "open", "reveal"]

[[open.rules]]
mime = "text/*"
use = ["edit", "reveal"]

[[open.rules]]
mime = "image/*"
use = ["open", "reveal"]

[[open.rules]]
mime = "{audio,video}/*"
use = ["play", "reveal"]

[[open.rules]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
use = ["extract", "reveal"]

[[open.rules]]
mime = "application/{json,ndjson}"
use = ["edit", "reveal"]

[[open.rules]]
mime = "*/javascript"
use = ["edit", "reveal"]

[[open.rules]]
mime = "inode/empty"
use = ["edit", "reveal"]

[[open.rules]]
url = "*"
use = ["open", "reveal"]

[[opener.edit]]
block = true
desc = "$EDITOR"
for = "unix"
run = "${EDITOR} \"$@\""

[[opener.edit]]
desc = "code"
for = "windows"
orphan = true
run = "code %*"

[[opener.edit]]
block = true
desc = "code (block)"
for = "windows"
run = "code -w %*"

[[opener.extract]]
desc = "Extract here"
for = "unix"
run = "ya pub extract --list \"$@\""

[[opener.extract]]
desc = "Extract here"
for = "windows"
run = "ya pub extract --list %*"

[[opener.helix]]
block = true
desc = "Helix"
for = "unix"
run = "hx \"$@\""

[[opener.open]]
desc = "Open"
for = "linux"
run = "xdg-open \"$1\""

[[opener.open]]
desc = "Open"
for = "macos"
run = "open \"$@\""

[[opener.open]]
desc = "Open"
for = "windows"
orphan = true
run = "start \"\" \"%1\""

[[opener.play]]
for = "unix"
orphan = true
run = "mpv --force-window \"$@\""

[[opener.play]]
for = "windows"
orphan = true
run = "mpv --force-window %*"

[[opener.play]]
block = true
desc = "Show media info"
for = "unix"
run = "mediainfo \"$1\"; echo \"Press enter to exit\"; read _"

[[opener.reveal]]
desc = "Reveal"
for = "linux"
run = "xdg-open \"$(dirname \"$1\")\""

[[opener.reveal]]
desc = "Reveal"
for = "macos"
run = "open -R \"$1\""

[[opener.reveal]]
desc = "Reveal"
for = "windows"
orphan = true
run = "explorer /select,\"%1\""

[[opener.reveal]]
block = true
desc = "Show EXIF"
for = "unix"
run = "exiftool \"$1\"; echo \"Press enter to exit\"; read _"

[pick]
open_offset = [0, 1, 50, 7]
open_origin = "hovered"
open_title = "Open with:"

[[plugin.append_previewers]]
run = "piper -- hexyl --border=none --terminal-width=$w \"$1\""
url = "*"

[[plugin.fetchers]]
id = "mime"
prio = "high"
run = "mime.dir"
url = "*/"

[[plugin.fetchers]]
id = "mime"
prio = "high"
run = "mime.local"
url = "local://*"

[[plugin.fetchers]]
id = "mime"
prio = "high"
run = "mime.remote"
url = "remote://*"

[[plugin.preloaders]]
mime = "image/{avif,hei?,jxl}"
run = "magick"

[[plugin.preloaders]]
mime = "image/svg+xml"
run = "magick"

[[plugin.preloaders]]
mime = "image/*"
run = "image"

[[plugin.preloaders]]
mime = "video/*"
run = "video"

[[plugin.preloaders]]
mime = "application/pdf"
run = "pdf"

[[plugin.preloaders]]
mime = "font/*"
run = "font"

[[plugin.preloaders]]
mime = "application/ms-opentype"
run = "font"

[[plugin.prepend_previewers]]
run = "piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark \"$1\""
url = "*.md"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.csv"

[[plugin.prepend_previewers]]
run = "piper --format=url -- tar tf \"$1\""
url = "*.tar*"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.log"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.{conf,config,cfg,ini,toml,yaml,yml}"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.{sh,bash,zsh,fish}"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.py"

[[plugin.prepend_previewers]]
run = "piper -- jq . \"$1\" 2>/dev/null || bat -p --color=always \"$1\""
url = "*.json"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "*.xml"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = "Dockerfile*"

[[plugin.prepend_previewers]]
run = "piper -- bat -p --color=always \"$1\""
url = ".git*"

[[plugin.previewers]]
run = "folder"
sync = true
url = "*/"

[[plugin.previewers]]
mime = "text/*"
run = "code"

[[plugin.previewers]]
mime = "application/{mbox,javascript,wine-extension-ini}"
run = "code"

[[plugin.previewers]]
mime = "application/{json,ndjson}"
run = "json"

[[plugin.previewers]]
mime = "image/{avif,hei?,jxl}"
run = "magick"

[[plugin.previewers]]
mime = "image/svg+xml"
run = "magick"

[[plugin.previewers]]
mime = "image/*"
run = "image"

[[plugin.previewers]]
mime = "video/*"
run = "video"

[[plugin.previewers]]
mime = "application/pdf"
run = "pdf"

[[plugin.previewers]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
run = "archive"

[[plugin.previewers]]
mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}"
run = "archive"

[[plugin.previewers]]
run = "archive"
url = "*.{AppImage,appimage}"

[[plugin.previewers]]
mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}"
run = "archive"

[[plugin.previewers]]
mime = "application/virtualbox-{vhd,vhdx}"
run = "archive"

[[plugin.previewers]]
run = "archive"
url = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}"

[[plugin.previewers]]
mime = "font/*"
run = "font"

[[plugin.previewers]]
mime = "application/ms-opentype"
run = "font"

[[plugin.previewers]]
mime = "inode/empty"
run = "empty"

[[plugin.previewers]]
run = "file"
url = "*"

[[plugin.spotters]]
run = "folder"
url = "*/"

[[plugin.spotters]]
mime = "text/*"
run = "code"

[[plugin.spotters]]
mime = "application/{mbox,javascript,wine-extension-ini}"
run = "code"

[[plugin.spotters]]
mime = "image/{avif,hei?,jxl}"
run = "magick"

[[plugin.spotters]]
mime = "image/svg+xml"
run = "magick"

[[plugin.spotters]]
mime = "image/*"
run = "image"

[[plugin.spotters]]
mime = "video/*"
run = "video"

[[plugin.spotters]]
run = "file"
url = "*"

[preview]
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
max_height = 1000
max_width = 1200
tab_size = 2
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1
wrap = "no"

[tasks]
bizarre_retry = 3
image_alloc = 536870912
image_bound = [0, 0]
macro_workers = 10
micro_workers = 10
suppress_preload = false

[which]
sort_by = "none"
sort_reverse = false
sort_sensitive = false
sort_translit = false
